"use client";

import React from 'react';
import { motion } from 'framer-motion';
import { Download, FileText, FileJson } from 'lucide-react';

interface ExportButtonProps {
  data: any;
  filename?: string;
}

export default function ExportButton({ data, filename = 'verification-result' }: ExportButtonProps) {
  
  const exportAsJSON = () => {
    const jsonString = JSON.stringify(data, null, 2);
    const blob = new Blob([jsonString], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${filename}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const exportAsText = () => {
    let textContent = `HALLUX VERIFICATION REPORT\n`;
    textContent += `${'='.repeat(80)}\n\n`;
    textContent += `Citation: ${data.citation || 'N/A'}\n`;
    textContent += `Timestamp: ${data.metadata?.timestamp || new Date().toISOString()}\n`;
    textContent += `Overall Status: ${data.status || 'N/A'}\n`;
    textContent += `Confidence Score: ${data.confidence || 0}%\n\n`;
    
    textContent += `VERIFICATION LAYERS:\n`;
    textContent += `${'-'.repeat(80)}\n`;
    
    const layers = data.verification_layers || {};
    for (const [layerName, layerData] of Object.entries(layers)) {
      const layer = layerData as any;
      textContent += `\n${layerName.toUpperCase().replace(/_/g, ' ')}:\n`;
      textContent += `  Status: ${layer.status || 'N/A'}\n`;
      textContent += `  Details: ${layer.details || 'No details'}\n`;
      if (layer.confidence !== null) {
        textContent += `  Confidence: ${(layer.confidence * 100).toFixed(1)}%\n`;
      }
    }
    
    if (data.ai_reasoning) {
      textContent += `\n\nAI ANALYSIS:\n`;
      textContent += `${'-'.repeat(80)}\n`;
      textContent += `${data.ai_reasoning}\n`;
    }
    
    if (data.suggestions && data.suggestions.length > 0) {
      textContent += `\n\nSUGGESTED ALTERNATIVES:\n`;
      textContent += `${'-'.repeat(80)}\n`;
      data.suggestions.forEach((suggestion: any, index: number) => {
        textContent += `\n${index + 1}. ${suggestion.title}\n`;
        textContent += `   Authors: ${suggestion.authors?.join(', ') || 'N/A'}\n`;
        textContent += `   Year: ${suggestion.year || 'N/A'}\n`;
        textContent += `   DOI: ${suggestion.doi || 'N/A'}\n`;
      });
    }
    
    textContent += `\n\n${'='.repeat(80)}\n`;
    textContent += `Generated by Hallux AI - Citation Verification System\n`;
    textContent += `https://hallux.ai\n`;
    
    const blob = new Blob([textContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${filename}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex gap-3">
      <motion.button
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        onClick={exportAsJSON}
        className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition-colors"
      >
        <FileJson size={18} />
        <span>Export JSON</span>
      </motion.button>
      
      <motion.button
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        onClick={exportAsText}
        className="flex items-center gap-2 px-4 py-2 bg-gray-600 hover:bg-gray-700 text-white rounded-lg font-medium transition-colors"
      >
        <FileText size={18} />
        <span>Export TXT</span>
      </motion.button>
    </div>
  );
}
